version: '3.9'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - ./config.conf:/var/lib/neo4j/conf/neo4j.conf
    ports:
      - "7474:7474"
      - "7687:7687"
volumes:
  neo4j_data: