version: "3.9"
services:
  sonarqube:
    image: sonarqube:community
    environment:
      ORACLE_ENABLE_XDB: true
    ports:
      - "19000:9000"
      - "18080:8080"
    networks:
      - anyops-net
networks:
  anyops-net:
    name: anyops-net