version: '3.9'
services:
  mlflow_minio:
    image: minio/minio:RELEASE.2022-10-15T19-57-03Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ':9001' --address ':9000'
    volumes:
      - mlflow_minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - env_file
  mlflow_postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - mlflow_postgresql_data:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file:
      - env_file
  mlflow_server:
    restart: always
    build: ./
    image: anyops/mlflow_server
    ports:
      - "5000:5000"
    command: 'mlflow server --default-artifact-root s3://mlflow/ --host 0.0.0.0'
    environment:
      - AWS_ACCESS_KEY_ID=$${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=$${MINIO_ROOT_PASSWORD}
      - MLFLOW_TRACKING_URI=postgresql://$${POSTGRESQL_USERNAME}:$${POSTGRESQL_PASSWORD}@mlflow_postgresql:5432/$${POSTGRESQL_DATABASE}
      - MLFLOW_S3_ENDPOINT_URL=http://mlflow_minio:9000
    env_file:
      - env_file
volumes:
  mlflow_minio_data:
  mlflow_postgresql_data: